# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21b8a5d762f2a640b98a026b06306cfc927935e7cc7fe512cb2d8dba56a8b91c81c62e28bf091905c7f9be48bbaad7a4097991a8b87c95195b324740d7b043f8

test:
  secret_key_base: 1b874d34bb79d9d021bad61148ed5f0f8a455f77c97c9389cbdd01618b5c83a5cdd354732d731611ec5e0b6b1e00f74fc193be1da05e8293c4e4290f3eeb330b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
